[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
interpreter = { version = "0.1.0", path = "../interpreter" }
parser = { version = "0.1.0", path = "../parser" }
wasm-bindgen = "0.2"
