name: Rust and WASM CI

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          cargo test

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Build with wasm-pack
        run: wasm-pack build ./playground --target web

      - name: Prepare files for deployment
        run: |
          mkdir -p deployment_directory
          cp -r ./playground/pkg/* deployment_directory/
          cp -r ./playground/web/* deployment_directory/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deployment_directory
